from get_pc_usage_stats.get_pc_usage import get_pc_dataframe
from get_pc_usage_stats.get_pc_usage import get_pc_avg_cpu_temp

#from get_pc_usage import get_pc_dataframe
#from get_pc_usage import get_pc_avg_cpu_temp